plugins {
    id 'java'
    id 'idea'
    alias(libs.plugins.spring.boot) apply false
}

group = 'com.base'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

idea {
    project {
        languageLevel = 25
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    test {
        useJUnitPlatform()
    }
}